/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica a disponibilidade da API */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria uma conta individual */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia uma sessão */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova a sessão atual */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoga a sessão atual */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna o usuário autenticado */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/periodos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista períodos do usuário */
        get: operations["listPeriodos"];
        put?: never;
        /** Cria um período */
        post: operations["createPeriodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/periodos/{periodoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        /** Obtém um período */
        get: operations["getPeriodo"];
        put?: never;
        post?: never;
        /** Remove um período */
        delete: operations["deletePeriodo"];
        options?: never;
        head?: never;
        /** Atualiza um período */
        patch: operations["updatePeriodo"];
        trace?: never;
    };
    "/periodos/{periodoId}/disciplinas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        /** Lista disciplinas de um período */
        get: operations["listDisciplinas"];
        put?: never;
        /** Cria uma disciplina */
        post: operations["createDisciplina"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/disciplinas/{disciplinaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        /** Obtém uma disciplina */
        get: operations["getDisciplina"];
        put?: never;
        post?: never;
        /** Remove uma disciplina */
        delete: operations["deleteDisciplina"];
        options?: never;
        head?: never;
        /** Atualiza uma disciplina */
        patch: operations["updateDisciplina"];
        trace?: never;
    };
    "/disciplinas/{disciplinaId}/tarefas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        /** Lista tarefas de uma disciplina */
        get: operations["listTarefas"];
        put?: never;
        /** Cria uma tarefa */
        post: operations["createTarefa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tarefas/{tarefaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tarefaId: components["parameters"]["TarefaId"];
            };
            cookie?: never;
        };
        /** Obtém uma tarefa */
        get: operations["getTarefa"];
        put?: never;
        post?: never;
        /** Remove uma tarefa */
        delete: operations["deleteTarefa"];
        options?: never;
        head?: never;
        /** Atualiza uma tarefa */
        patch: operations["updateTarefa"];
        trace?: never;
    };
    "/disciplinas/{disciplinaId}/provas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        /** Lista provas de uma disciplina */
        get: operations["listProvas"];
        put?: never;
        /** Cria uma prova */
        post: operations["createProva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provas/{provaId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provaId: components["parameters"]["ProvaId"];
            };
            cookie?: never;
        };
        /** Obtém uma prova */
        get: operations["getProva"];
        put?: never;
        post?: never;
        /** Remove uma prova */
        delete: operations["deleteProva"];
        options?: never;
        head?: never;
        /** Atualiza uma prova */
        patch: operations["updateProva"];
        trace?: never;
    };
    "/periodos/{periodoId}/horarios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        /** Lista a grade-tipo de um período */
        get: operations["listHorarios"];
        put?: never;
        /** Cria um horário semanal */
        post: operations["createHorario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/horarios/{horarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        /** Obtém um horário */
        get: operations["getHorario"];
        put?: never;
        post?: never;
        /** Remove um horário */
        delete: operations["deleteHorario"];
        options?: never;
        head?: never;
        /** Atualiza um horário */
        patch: operations["updateHorario"];
        trace?: never;
    };
    "/horarios/{horarioId}/cancelamentos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        /** Lista os cancelamentos de um horário */
        get: operations["listCancelamentos"];
        put?: never;
        /** Cancela uma instância de aula */
        post: operations["createCancelamento"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cancelamentos/{cancelamentoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancelamentoId: components["parameters"]["CancelamentoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove um cancelamento */
        delete: operations["deleteCancelamento"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** @example rota-de-estudo-api */
            service: string;
            /** @example 0.1.0 */
            version: string;
            /** Format: date-time */
            timestamp: string;
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /**
             * @default pt-BR
             * @enum {string}
             */
            locale: "pt-BR" | "en";
            /** @default America/Recife */
            timezone: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            /** Format: date-time */
            expiresAt: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            locale: "pt-BR" | "en";
            /** @example America/Recife */
            timezone: string;
            /** Format: date-time */
            createdAt: string;
        };
        PeriodoRequest: {
            name: string;
            /** Format: date */
            startsOn?: string | null;
            /** Format: date */
            endsOn?: string | null;
            status?: components["schemas"]["PeriodoStatus"];
        };
        Periodo: components["schemas"]["PeriodoRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        PeriodoStatus: "ABERTO" | "ARQUIVADO";
        DisciplinaRequest: {
            name: string;
            color?: string | null;
        };
        Disciplina: components["schemas"]["DisciplinaRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            periodoId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TarefaRequest: {
            title: string;
            description?: string | null;
            type: components["schemas"]["TarefaTipo"];
            priority: components["schemas"]["Prioridade"];
            status?: components["schemas"]["TarefaStatus"];
            /** Format: date-time */
            dueAt?: string | null;
            /** Format: date-time */
            completedAt?: string | null;
            tags?: string[];
        };
        Tarefa: components["schemas"]["TarefaRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            disciplinaId: string;
            status: components["schemas"]["TarefaStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        TarefaTipo: "TAREFA" | "TRABALHO" | "OUTRO";
        /** @enum {string} */
        Prioridade: "BAIXA" | "MEDIA" | "ALTA";
        /** @enum {string} */
        TarefaStatus: "PENDENTE" | "CONCLUIDA";
        ProvaRequest: {
            title: string;
            /** Format: date-time */
            startsAt: string;
            weight: number;
            grade?: number | null;
            notes?: string | null;
        };
        Prova: components["schemas"]["ProvaRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            disciplinaId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        HorarioRequest: {
            /** Format: uuid */
            disciplinaId: string;
            weekday: components["schemas"]["Weekday"];
            /**
             * Format: time
             * @example 08:00
             */
            startsAt: string;
            /**
             * Format: time
             * @example 09:50
             */
            endsAt: string;
        };
        Horario: components["schemas"]["HorarioRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            periodoId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description MONDAY=1, TUESDAY=2, WEDNESDAY=3, THURSDAY=4, FRIDAY=5, SATURDAY=6, SUNDAY=7.
         * @enum {string}
         */
        Weekday: "MONDAY" | "TUESDAY" | "WEDNESDAY" | "THURSDAY" | "FRIDAY" | "SATURDAY" | "SUNDAY";
        CancelamentoRequest: {
            /** Format: date */
            date: string;
            reason?: string | null;
        };
        Cancelamento: components["schemas"]["CancelamentoRequest"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            horarioId: string;
            /** Format: date-time */
            createdAt: string;
        };
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        PeriodoPage: {
            content: components["schemas"]["Periodo"][];
            page: components["schemas"]["PageMeta"];
        };
        DisciplinaPage: {
            content: components["schemas"]["Disciplina"][];
            page: components["schemas"]["PageMeta"];
        };
        TarefaPage: {
            content: components["schemas"]["Tarefa"][];
            page: components["schemas"]["PageMeta"];
        };
        ProvaPage: {
            content: components["schemas"]["Prova"][];
            page: components["schemas"]["PageMeta"];
        };
        ApiError: {
            /** @example VALIDATION_ERROR */
            code: string;
            message: string;
            /** Format: uuid */
            requestId: string;
            /** Format: date-time */
            timestamp: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Requisição inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Sessão ausente ou inválida */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Recurso não encontrado ou não pertencente ao usuário */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Conflito com um recurso existente */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Limite de requisições excedido */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        PeriodoId: string;
        DisciplinaId: string;
        TarefaId: string;
        ProvaId: string;
        HorarioId: string;
        CancelamentoId: string;
        IncludeArchived: boolean;
        Page: number;
        Size: number;
        TaskStatus: components["schemas"]["TarefaStatus"];
        /** @description Limite inicial inclusivo em ISO-8601. */
        From: string;
        /** @description Limite final exclusivo em ISO-8601. */
        To: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API disponível */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Conta criada */
            201: {
                headers: {
                    /** @description Cookie de sessão httpOnly */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sessão iniciada */
            200: {
                headers: {
                    /** @description Cookie de sessão httpOnly */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão renovada */
            200: {
                headers: {
                    /** @description Cookie de sessão httpOnly rotacionado */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão revogada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPeriodos: {
        parameters: {
            query?: {
                includeArchived?: components["parameters"]["IncludeArchived"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de períodos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodoPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPeriodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeriodoRequest"];
            };
        };
        responses: {
            /** @description Período criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Periodo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPeriodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Período */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Periodo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePeriodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Período removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePeriodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeriodoRequest"];
            };
        };
        responses: {
            /** @description Período atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Periodo"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDisciplinas: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de disciplinas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisciplinaPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createDisciplina: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisciplinaRequest"];
            };
        };
        responses: {
            /** @description Disciplina criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disciplina"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getDisciplina: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disciplina */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disciplina"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDisciplina: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disciplina removida */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateDisciplina: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisciplinaRequest"];
            };
        };
        responses: {
            /** @description Disciplina atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disciplina"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTarefas: {
        parameters: {
            query?: {
                status?: components["parameters"]["TaskStatus"];
                /** @description Limite inicial inclusivo em ISO-8601. */
                from?: components["parameters"]["From"];
                /** @description Limite final exclusivo em ISO-8601. */
                to?: components["parameters"]["To"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de tarefas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TarefaPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createTarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TarefaRequest"];
            };
        };
        responses: {
            /** @description Tarefa criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tarefa"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tarefaId: components["parameters"]["TarefaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tarefa */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tarefa"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tarefaId: components["parameters"]["TarefaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tarefa removida */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTarefa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tarefaId: components["parameters"]["TarefaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TarefaRequest"];
            };
        };
        responses: {
            /** @description Tarefa atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tarefa"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProvas: {
        parameters: {
            query?: {
                /** @description Limite inicial inclusivo em ISO-8601. */
                from?: components["parameters"]["From"];
                /** @description Limite final exclusivo em ISO-8601. */
                to?: components["parameters"]["To"];
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de provas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvaPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createProva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                disciplinaId: components["parameters"]["DisciplinaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvaRequest"];
            };
        };
        responses: {
            /** @description Prova criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prova"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provaId: components["parameters"]["ProvaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prova */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prova"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provaId: components["parameters"]["ProvaId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prova removida */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateProva: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provaId: components["parameters"]["ProvaId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProvaRequest"];
            };
        };
        responses: {
            /** @description Prova atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prova"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listHorarios: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Horários do período */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Horario"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createHorario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                periodoId: components["parameters"]["PeriodoId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioRequest"];
            };
        };
        responses: {
            /** @description Horário criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Horario"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getHorario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Horário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Horario"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteHorario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Horário removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateHorario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HorarioRequest"];
            };
        };
        responses: {
            /** @description Horário atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Horario"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listCancelamentos: {
        parameters: {
            query?: {
                /** @description Limite inicial inclusivo em ISO-8601. */
                from?: components["parameters"]["From"];
                /** @description Limite final exclusivo em ISO-8601. */
                to?: components["parameters"]["To"];
            };
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelamentos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancelamento"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createCancelamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                horarioId: components["parameters"]["HorarioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelamentoRequest"];
            };
        };
        responses: {
            /** @description Cancelamento criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cancelamento"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCancelamento: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cancelamentoId: components["parameters"]["CancelamentoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelamento removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
